services:
  backend:
    image: gitea.mohandl3g.ddnsgeek.com/mohandl3g/pc-achievements-backend:latest
    container_name: pc-achievements-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/achievements.db:/usr/src/app/achievements.db
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: docker.angie.software/angie:latest
    container_name: pc-achievements-frontend
    volumes:
      - ./frontend/dist:/usr/share/angie/html:ro
      - ./frontend/angie.conf:/etc/angie/http.d/default.conf:ro
    ports:
      - "480:80"
    healthcheck:
      test: ["CMD", "angie", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend
    restart: unless-stopped
